### ISSUE TITLE
Malware not download

### ISSUE THREAD

**Issue by jjjan** [dtag-dev-sec/dtag-dev-sec.github.io#3]
Hello
 after a month running of tpot dionaea and honeytrap don't download any malware sample.
what should i do?

**Comment by t3chn0m4g3** [comment]
@jjjan Can you be more specific please? If you are running T-Pot 16.03 please be aware that all container data will be deleted every 24h. Please have a look [here](https://github.com/dtag-dev-sec/tpotce/issues/28) on how to enable persistence.

**Comment by jjjan** [comment]
as you know dionaea honeypot should capture malware and save it in disk. also in honeytrap we should have binary of malware. does tpot save malware ? (i am running T-Pot 16.03)

**Comment by t3chn0m4g3** [comment]
Did you read my previous comment? How often do you check for malicious files? Every night all data will be removed and you start with a fresh container and empty storage unless you enable persistence.

**Comment by jjjan** [comment]
yeap thanks indeed
