### ISSUE TITLE
Dashboards don't show world map; Error: "Coordinate Map: Could not retrieve manifest from the tile service: status -1"

### ISSUE THREAD

**Issue by musevg** [dtag-dev-sec/dtag-dev-sec.github.io#7]
Sorry if this isn't the right place for this issue of if this has been resolved already:
I used the autoinstall script to install multiple T-Pots over the last years, the last ones were 17.10 on 
Ubuntu 16.04.4. One issue I come across in T-Pot 17.10 is....
When I open any of the dashboards (T-Pot or Cowrie or...), there's a "Attack map" on the upper 
right hand side, with filled circles of different colours and sizes. I guess I know this map from 
earlier T-Pot versions, where there was a world map in the background. But now, the background 
is only white, no world map. 
Also there's a orange message box at the top of the dashboard for ~10 seconds when I open 
the dashboards. It reads "Coordinate Map: Could not retrieve manifest from the tile service: status -1".
As I'm an ELK n00b, I can't fix this myself :(

**Comment by t3chn0m4g3** [comment]
In the future please open issues in tpotce or t-pot-autoinstall repositories. Thank You.

The map is loaded from within your browser. If it does not show it means your browser cannot access the tiles, hence the orange box message.
