### ISSUE TITLE
2015-03-17-concept.markdown - stale link? 

### ISSUE THREAD

**Issue by evilon** [dtag-dev-sec/dtag-dev-sec.github.io#8]
The background section of the page [2015-03-17-concept.markdown](
https://github.com/dtag-dev-sec/dtag-dev-sec.github.io/blob/master/_posts/2015-03-17-concept.markdown#background) provides two links:  [Sicherheitstacho](http://sicherheitstacho.eu/) / [Securitydashboard](http://securitydashboard.eu/).

However, the link "Securitydashboard"  results in ERR_NAME_NOT_RESOLVED.  Accessed: 2018-07-02.

**Comment by hillar** [comment]
mhmh..

Domain: securitydashboard.eu
Status: AVAILABLE

**Comment by ghost** [comment]
Ji Hillar, thx,

Markus?

Best regards

Markus

On 2. Jul 2018, at 22:05, Hillar <notifications@github.com<mailto:notifications@github.com>> wrote:


mhmh..

Domain: securitydashboard.eu<http://securitydashboard.eu>
Status: AVAILABLE

**Comment by AlpixTM** [comment]
Now the domain is owned by another person, not by the Telekom anymore.
So I think its really time to remove the link...

I opened a pull request (#9) removing the link, maybe this brings the attention of @dtag-dev-sec / @t3chn0m4g3 or @vorband to this.

**Comment by sp3t3rs** [comment]
Hello all,

many thanks for the hint! :pray: Originally we wanted to use this domain too, but in the end we only used sicherheitstacho.eu. However, it's planned to offer an english domain in the future :+1: 

Cheers
Simon

**Comment by ziehmon** [comment]
Hello all,

many thanks for the hint! :pray: Originally we wanted to use this domain too, but in the end we only used sicherheitstacho.eu. However, it's planned to offer an english domain in the future :+1: 

Cheers
Simon
